stages:
  - build
  - test
  - publish

build:
  stage: build
  image: node:lts-alpine
  cache:
    paths:
      - node_modules/
  tags:
    - docker
    - gitlab
  script:
    - yarn
    - yarn build


test:
  stage: test
  image: node:lts-alpine
  cache:
    paths:
      - node_modules/
  tags:
    - docker
    - gitlab
  script:
    - yarn
    - yarn test

publish:
  stage: publish
  image: node:lts-alpine
  cache:
    paths:
      - node_modules/
  tags:
    - docker
    - gitlab
  script:
    - yarn
    - yarn publish --non-interactive
  when: manual
  allow_failure: true