stages:
  - publish

publish:
  stage: publish
  image: node:lts-alpine
  cache:
    paths:
      - node_modules/
  tags:
    - docker
    - gitlab
  script:
    - yarn
    - yarn publish --non-interactive